### ISSUE TITLE
Personalize repo

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/shanghai#1]
We've provided a basic readme for you, but you should personalize it for your own
chapter's needs. You might want to:

- adjust the welcome section
- add some regional flair (like Mumbai's multi-language welcome or Seattle's emojis 🌲🗻☔️)
- include additional contact info for organizers (email, Twitter, etc.)
- mention related Meetup groups that will be hosting your ProtoSchool events
- request help planning upcoming events
- call for co-organizers to join you
- add calls to action (see below)

When someone learns of your ProtoSchool chapter for the first time by visiting your repo's readme, what would you like them to do next? Providing a clear *call to action* is a best practice for making newcomers feel welcome and increasing community involvement.

How can your members learn about upcoming events? Will they be published at a Meetup website that you've linked to? Will they be announced in an issue in your repo ([example](https://github.com/ProtoSchool/Denver/issues/3)), which means they should watch the repo to be notified?

Do you need help planning your next event, perhaps in the form of mentors or meeting space? Try opening an issue in your repo for event planning ([example](https://github.com/ProtoSchool/san-francisco/issues/1)) and linking to it from your readme file with a friendly "Help us plan our next event!" message.

Do you need co-organizers? If so, tell them who they should reach out to (and how) to offer their help ([example](https://github.com/ProtoSchool/Denver#denvers-organizer-team)).

The processes you use to communicate with your members are up to you, but you should aim to make it clear from the readme how people can get involved and stay up-to-date.

**Comment by steven004** [comment]
Readme updated and a Chinese version is provided. Please review and merge.

**Comment by steven004** [comment]
updated and merged, please see if this issue could be closed.

**Comment by terichadbourne** [comment]
I’m happy to have you close this out as soon as the co-organizers feel comfortable with it. 🏆

**Comment by terichadbourne** [comment]
Just circling back to confirm that @DjangoPeng is comfortable with all the repo personalization. If so, feel free to close out this issue.

**Comment by DjangoPeng** [comment]
Finish setting up shanghai chapter.

Close the issue.
