### ISSUE TITLE
Review Code of Conduct

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/shanghai#2]
We've provided a draft Code of Conduct for you that includes the contact information you provided for reporting purposes. Please ensure that these contact details are correct.

Please ensure that all chapter organizers have reviewed the CoC thoroughly and are comfortable enforcing it. 

(This will need to be done before we can list your chapter on our website.)

**Optional:** Our tutorials are currently all in English, but If you decide that you'll be conducting your chapter events and repo discussions in a language other than English, you are welcome to update your Code of Conduct to the appropriate language. What's used right now is a custom Code of Conduct that mixes the [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct) ([see available translations](https://www.contributor-covenant.org/translations)) with the [Conference Code of Conduct](http://confcodeofconduct.com/) ([see available translations](https://github.com/confcodeofconduct/confcodeofconduct.com)) to ensure it covers interactions both online and at events.

**Comment by terichadbourne** [comment]
@DjangoPeng @steven004 Are you now both comfortable with both versions of the Code of Conduct? If so, please go ahead and close out this issue.

**Comment by DjangoPeng** [comment]
Finish setting up shanghai chapter.

Close the issue.
