### ISSUE TITLE
Add your chapter to our listings

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/shanghai#3]
Once issues #1 & #2 are complete, please complete Step 5 in the [chapter setup instructions](https://github.com/ProtoSchool/organizing#how-to-start-a-new-protoschool-chapter) by opening a pull request to have your chapter included in the [list of ProtoSchool chapters](https://proto.school/#/chapters).

Please be sure to include the `repo` field so that your listing will link to this chapter repo. Should you decide that you'd like your listing to go to a website instead (now or in the future), you can add an additional `website` field with the appropriate URL, which will update the link.

**Comment by terichadbourne** [comment]
@DjangoPeng @steven004 Quick reminder that Shanghai is not yet included in our chapter listings. Please let me know if you have any questions on the process of making that happen.

**Comment by DjangoPeng** [comment]
@terichadbourne Sorry for missing the info. Just finish the holiday of Chinese Spring Festival. I'll create a PR today later to solve the issues.

@steven004 might be on vacation as well. I'll collaborate with him to do this together.

**Comment by DjangoPeng** [comment]
PTAL https://github.com/ProtoSchool/protoschool.github.io/pull/156

**Comment by DjangoPeng** [comment]
Finish setting up shanghai chapter.

Close the issue.

**Comment by steven004** [comment]
@terichadbourne , I sent you a message to your personal email account, which I found in your profile, about our first event to be held on next Tuesday, and hoping to get your support. But, I am not sure if you got it. Would you please check, and let me know if there is any issue. Thanks.

**Comment by terichadbourne** [comment]
@steven004 Just found your email but am out dealing with a family medical emergency. I'll double-check with colleagues and do my best to get back to you later in the week.

**Comment by steven004** [comment]
Thanks, Teri. Take your time.

Hope everything with your family getting well soon.
